### PR TITLE
New float widget: clientmenu

### PR DESCRIPTION
**Pull request by M4he**
### Please note

I made this widget primarily for my own use case but thought I'd try providing it upstream. Feel free to reject it if you see no use for it or if you think it does not fit into the idea of redflat.

I tried my best matching the code style and quality to the existing widgets. If there's any issue with the code I'm always open for suggestions. You don't have to pull this right away.

Please tell me if such addition would be of interest for you.

## Preface

Being a hybrid mouse/keyboard user and preferably using full size titlebars on my desktop system, I often found myself longing for a way to manage clients (especially close/minimize) by mouse without traveling the whole way down to the tasklist.

## Description

This new float (widget) introduces a new stand-alone popup menu that partly mimics the `tasklist.winmenu`. Instead of the client's name it shows two big buttons for minimize and close respectively, which are easy to access. Those two buttons will also make the menu hide upon press in contrast to the existing menu elements.

It is useful for:
- titlebar right-click popup (full size titlebars especially)
- custom keybind shortcut to popup at cursor position for active client

clientmenu

I borrowed some code from the `redflat.widget.tasklist.winmenu` widget but made a stand-alone float. It therefore has some code duplication with `redflat.widget.tasklist.winmenu` obviously.

## Example config for colorless

If you want to try it out, this menu can be integrated very easily into existing themes. It works well by simply copying the style config from the `tasklist.winmenu`. Below is an example for the `colorless` config and theme to use it as a titlebar right-click popup menu.

Diff for `colorless/titlebar-config.lua`:

    @@ -8,6 +8,7 @@ local wibox = require("wibox")
     
     -- local redflat = require("redflat")
     local redtitle = require("redflat.titlebar")
    +local clientmenu = require("redflat.float.clientmenu")
     
     -- Initialize tables and vars for module
     -----------------------------------------------------------------------------------------------------------------------
    @@ -23,6 +24,13 @@ local function title_buttons(c)
                                    client.focus = c;  c:raise()
                                    awful.mouse.client.move(c)
                            end
    +               ),
    +               awful.button(
    +                       { }, 3,
    +                       function()
    +                               client.focus = c;  c:raise()
    +                               clientmenu:show(c)
    +                       end
                    )
            )
     end
    @@ -50,6 +58,8 @@ function titlebar:init(args)
            style.light = args.light or redtitle.get_style()
            style.full = args.full or { size = 28, icon = { size = 25, gap = 0, angle = 0.5 } }
     
    +       clientmenu:init()
    +
            client.connect_signal(
                    "request::titlebars",
                    function(c)

Diff for `themes/colorless/theme.lua`:

    @@ -332,6 +332,19 @@ theme.widget.tasklist.winmenu.icon = {
            maximized            = theme.path .. "/common/window_control/maximized.svg",
     }
     
    +-- Clientmenu
    +------------------------------------------------------------
    +theme.widget.clientmenu = {
    +       micon          = theme.icon,
    +       color          = theme.color,
    +       actionline     = { height = 28 },
    +       layout_icon    = theme.widget.layoutbox.icon,
    +       menu           = theme.widget.tasklist.winmenu.menu,
    +       state_iconsize = theme.widget.tasklist.winmenu.state_iconsize,
    +       tagmenu        = theme.widget.tasklist.winmenu.tagmenu,
    +       icon           = theme.widget.tasklist.winmenu.icon,
    +}
    +
     -- task aliases
     theme.widget.tasklist.appnames = {}
     theme.widget.tasklist.appnames["Firefox"             ] = "FIFOX"

### CODE REVIEW

**Comment by worron** [comment]
I like this work both in term of code and widget aesthetic. I really would like include this in `redflat` module, but there is major issue: indentation. Rule 'tabs for indentation, spaces for alignment' used in my module all the way. It may be a bit complicated and requires showing whitespaces in your editor, but offers great flexibility in return. You can switch real indent width without damaging code formatting.
```
local function default_style()
--->local style = {
--->--->color = { main = "#b1222b", icon = "#a0a0a0",
--->--->••••••••••gray = "#404040", highlight = "#eeeeee" },
--->}
--->return style
end
```
```
local function default_style()
->local style = {
->->color = { main = "#b1222b", icon = "#a0a0a0",
->->••••••••••gray = "#404040", highlight = "#eeeeee" },
->}
->return style
end
```
```
local function default_style()
------->local style = {
------->------->color = { main = "#b1222b", icon = "#a0a0a0",
------->------->••••••••••gray = "#404040", highlight = "#eeeeee" },
------->}
------->return style
end
```
Sorry, unless code follows this rule it can't be included to `redflat` module.

Also there are few very minor thing to improve, I'll point it later.

**Comment by M4he** [comment]
> Rule 'tabs for indentation, spaces for alignment' used in my module all the way.

Major oversight on my part - should've turned on the display of whitespaces in my editor from the start, then I would've noticed this in your code earlier. Sorry about that.

But thanks for the examples, they were very intuitive and I got a hang of it very quickly! I've added a new commit that makes the code adhere to this rule.

**Comment by worron** [comment]
Good work, thank for your time. I think some minor fixes can go without discussion, you can just check tiny commits on this branch.

**Comment by M4he** [comment]
Thanks for taking your time to clean this up. I was a bit uncertain about the amount of layouts I used there, glad to see it cleaned up. Much appreciated!

**Pull request merged**
